### ISSUE TITLE
pytoulbar not working on python3.9 on Mac

### ISSUE THREAD

**Issue by g-poveda** [toulbar2/toulbar2#20]
Hello, i pip install pytoulbar2 on a python3.9 environment and it works without problem.
 but the ```import tb2``` are failing because it seems the .so library installed with the pytoulbar is a python3.8 lib : 

```
>>> os.listdir("my_env/python3.9/site-packages/pytoulbar2")
['__init__.py', '__pycache__', '.dylibs', 'pytoulbar2.py', 'pytb2.cpython-38-darwin.so']
```

```
import pytoulbar2
model = pytoulbar2.CFN()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/python3.9/site-packages/pytoulbar2/pytoulbar2.py", line 54, in __init__
    tb2.init()
NameError: name 'tb2' is not defined
```

resulting bug is this one. 
I'm fine to use python3.8 for now but maybe there is just a wheel build problem in your side for python>=3.9.

**Comment by g-poveda** [comment]
@tschiex the bug don't occur anymore on mac, and the cpython lib is compiled with py3.9, thanks!
