### ISSUE TITLE
Internal error when posting soft Alldifferent in Python

### ISSUE THREAD

**Issue by IgnaceBleukx** [toulbar2/toulbar2#36]
Hi, 

I'm using Toulbar2 for solving Max-CSP problem consisting of several AllDifferent constraints.
However, I am having some trouble getting the package to work.

Below I crafted a minimal example that produces a runtime error.

```python
import pytoulbar2 as tb2

model = tb2.CFN()

for i in range(1,7):
    model.AddVariable(f"x{i}", [1,2,3,4,5])

# model.AddAllDifferent(['x1', 'x2', 'x3', 'x4'], "salldiff")
model.AddAllDifferent(['x1', 'x2', 'x3', 'x4', 'x5', 'x6'], "salldiff")
# model.AddAllDifferent(['x3', 'x4'], "salldiff")

model.Dump("alldiff.cfn")
model.Solve()
```

produces this stacktrace:

```bash
0: 2(1) 
1: 0(1) 
2: 7(1) 
3: 0(1) 
4: 0(1) 
5: 0(1) 
6: 7(1) 0(1) 8(1) 9(1) 10(1) 
7: 12(5) 1(1) 
8: 12(5) 3(1) 
9: 12(5) 4(1) 
10: 12(5) 5(1) 
11: 12(5) 6(1) 
12: 7(1) 8(1) 9(1) 10(1) 11(1) 
==graph===
0:[[1,0,0,-]] (2,0,1,-) [[3,0,0,-]] [[4,0,0,-]] [[5,0,0,-]] [[6,0,0,-]] 
1:(0,0,1,-) [[7,0,0,-]] [[8,0,0,-]] [[9,0,0,-]] [[10,0,0,-]] [[11,0,0,-]] 
2:[[0,0,0,-]] (7,0,1,-) [[8,0,0,-]] [[9,0,0,-]] [[10,0,0,-]] [[11,0,0,-]] 
3:(0,0,1,-) [[7,-16012798675095096,0,-]] [[8,0,0,-]] [[9,0,0,-]] [[10,0,0,-]] [[11,0,0,-]] 
4:(0,0,1,-) [[7,-16012798675095096,0,-]] [[8,-16012798675095096,0,-]] [[9,0,0,-]] [[10,0,0,-]] [[11,0,0,-]] 
5:(0,0,1,-) [[7,-16012798675095096,0,-]] [[8,-16012798675095096,0,-]] [[9,-16012798675095096,0,-]] [[10,0,0,-]] [[11,0,0,-]] 
6:(0,0,1,-) (7,-16012798675095096,1,-) (8,-16012798675095096,1,-) (9,-16012798675095096,1,-) (10,-16012798675095096,1,-) [[11,0,0,-]] 
7:(1,0,1,-) [[12,0,0,-]] [[2,0,0,-]] (12,512409557603043100,1,-) [[3,16012798675095096,0,-]] (12,512409557603043100,1,-) [[4,16012798675095096,0,-]] (12,512409557603043100,1,-) [[5,16012798675095096,0,-]] (12,512409557603043100,1,-) [[6,16012798675095096,0,-]] (12,512409557603043100,1,-) 
8:[[1,0,0,-]] [[12,0,0,-]] [[2,0,0,-]] (12,512409557603043100,1,-) (3,0,1,-) (12,512409557603043100,1,-) [[4,16012798675095096,0,-]] (12,512409557603043100,1,-) [[5,16012798675095096,0,-]] (12,512409557603043100,1,-) [[6,16012798675095096,0,-]] (12,512409557603043100,1,-) 
9:[[1,0,0,-]] [[12,0,0,-]] [[2,0,0,-]] (12,512409557603043100,1,-) [[3,0,0,-]] (12,512409557603043100,1,-) (4,0,1,-) (12,512409557603043100,1,-) [[5,16012798675095096,0,-]] (12,512409557603043100,1,-) [[6,16012798675095096,0,-]] (12,512409557603043100,1,-) 
10:[[1,0,0,-]] [[12,0,0,-]] [[2,0,0,-]] (12,512409557603043100,1,-) [[3,0,0,-]] (12,512409557603043100,1,-) [[4,0,0,-]] (12,512409557603043100,1,-) (5,0,1,-) (12,512409557603043100,1,-) [[6,16012798675095096,0,-]] (12,512409557603043100,1,-) 
11:[[1,0,0,-]] [[12,0,0,-]] [[2,0,0,-]] (12,512409557603043100,1,-) [[3,0,0,-]] (12,512409557603043100,1,-) [[4,0,0,-]] (12,512409557603043100,1,-) [[5,0,0,-]] (12,512409557603043100,1,-) (6,0,1,-) (12,512409557603043100,1,-) 
12:(7,0,1,-) (8,0,1,-) (9,0,1,-) (10,0,1,-) (11,0,1,-) [[7,-512409557603043100,0,-]] [[8,-512409557603043100,0,-]] [[9,-512409557603043100,0,-]] [[10,-512409557603043100,0,-]] [[11,-512409557603043100,0,-]] [[7,-512409557603043100,0,-]] [[8,-512409557603043100,0,-]] [[9,-512409557603043100,0,-]] [[10,-512409557603043100,0,-]] [[11,-512409557603043100,0,-]] [[7,-512409557603043100,0,-]] [[8,-512409557603043100,0,-]] [[9,-512409557603043100,0,-]] [[10,-512409557603043100,0,-]] [[11,-512409557603043100,0,-]] [[7,-512409557603043100,0,-]] [[8,-512409557603043100,0,-]] [[9,-512409557603043100,0,-]] [[10,-512409557603043100,0,-]] [[11,-512409557603043100,0,-]] [[7,-512409557603043100,0,-]] [[8,-512409557603043100,0,-]] [[9,-512409557603043100,0,-]] [[10,-512409557603043100,0,-]] [[11,-512409557603043100,0,-]] 
ERROR cannot delete edge (11,6)
Traceback (most recent call last):
  File "/home/ignace/git/SlackImplication/toulbar_rooms.py", line 87, in <module>
    model.Solve(showSolutions=1, timeLimit=7200)
  File "/home/ignace/git/toulbar2/pytoulbar2/pytoulbar2.py", line 776, in Solve
    solved = self.CFN.solve()
pytoulbar2.pytb2.InternalError: ... internal error found, sorry!
```

I'm running on the latest version as build from source from github.
Any help resolving this would be greatly appreciated : )

Kind regards,
Ignace

**Comment by toulbar2** [comment]
Hi Ignace,
Unfortunately, dumping the model into a file does not work with flow-based or DP-based global cost functions.  Thanks for pointing out this issue. I would recommend replacing the "salldiff" keyword by "binary" (if the scope is small enough) or "salldiffkp". And recompile with the latest version.

**Comment by IgnaceBleukx** [comment]
Hi,
Thanks for the quick answer. 
It seems that the error does not come from dumping the file but during solve (unless the solve dumps it internally of course). When commenting the line `model.Dump()` the error remains.
Replacing the encoding to "salldiffkp" yields no solutions. Is that to be expected?

Just out of curiosity:
The binary encoding yields a solution of `[1,1,1,1,1,1]` which does not seem optimal. Do I need to specify an objective function too or is this encoded in the alldiff already?
For the actual application I'm trying I will have 30-40 vars so binary encoding is probably not the way to go.

**Comment by toulbar2** [comment]
Hi,
The model should have no solution if 6 variables for 5 values.
I found two nasty bugs related to "salldiffkp", and "binary" when compiled in Release mode. It should be corrected now!
